version: 2.1
jobs: 

  build:

    macos:
      xcode: 11.3.0

    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: cd PitchPerfect/ && xcodebuild test -scheme PitchPerfect -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3'
      - store_test_results:
          path: test_output
